[tool.poetry]
name = "ssb-datadoc-model"
version = "4.0.2"
description = "Data Model for use in Statistics Norway's Metadata system"
authors = ["Statistics Norway <stat-dev@ssb.no>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/statisticsnorway/ssb-datadoc-model"

packages = [{ include = "datadoc_model" }]

[tool.poetry.dependencies]
python = ">=3.10"
pydantic = ">=2.4.0"

[tool.poetry.dev-dependencies]
black = "*"
ipython = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
