
on:
  pull_request:

jobs:
  generate-python:
    runs-on: ubuntu-latest
    container: docker.io/koxudaxi/datamodel-code-generator:0.23.0
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - run: >
            datamodel-codegen
            --input-file-type jsonschema
            --input src/datadoc-json-schema/datadoc-json-schema.json
            --output-model-type pydantic_v2.BaseModel
            --force-optional
            --use-default
